# Generated by Django 6.0.2 on 2026-03-06 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signal_person_task_person_task_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='person',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.AddField(
            model_name='signal',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='signals', to='core.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
