# Generated by Django 6.0.2 on 2026-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_signal_person_remove_task_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
