# Generated by Django 6.0.2 on 2026-03-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_signal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='notes',
            new_name='description',
        ),
    ]
