# Generated by Django 6.0.2 on 2026-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_notes_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
