# Generated by Django 6.0.2 on 2026-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_person_birth_date_person_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bsn',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
