# Generated by Django 6.0.2 on 2026-03-12 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_bsn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Medewerker'), ('both', 'Beide')], default='both', max_length=20)),
                ('output_format', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], default='docx', max_length=10)),
                ('template_file', models.FileField(upload_to='document_templates/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(limit_choices_to={'category': 'document_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to='core.settingoption')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='generated_documents/')),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('generated', 'Gegenereerd'), ('archived', 'Gearchiveerd')], default='draft', max_length=20)),
                ('rendered_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='core.person')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='core.documenttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Tekst'), ('textarea', 'Lange tekst'), ('date', 'Datum'), ('number', 'Nummer'), ('boolean', 'Ja/Nee')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Handmatig'), ('person', 'Persoon'), ('organization', 'Organisatie'), ('student_profile', 'Studentprofiel'), ('employee_profile', 'Medewerkerprofiel')], default='manual', max_length=30)),
                ('source_path', models.CharField(blank=True, help_text='Bijv. first_name, full_name, birth_date, name', max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.documenttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
