# Generated by Django 6.0.2 on 2026-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documenttemplate_generateddocument_templatevariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='templatevariable',
            name='is_active',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatevariable',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
