# Generated by Django 6.0.2 on 2026-03-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_documenttemplate_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='street',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobCoachingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcoaching_periods', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcoaching_periods', to='core.person')),
                ('status', models.ForeignKey(limit_choices_to={'category': 'jobcoaching_status'}, on_delete=django.db.models.deletion.PROTECT, related_name='jobcoaching_periods', to='core.settingoption')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WageValuePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=255)),
                ('meeting_attendees', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'wage_value_decision_status'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wage_value_decisions', to='core.settingoption')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_value_periods', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_value_periods', to='core.person')),
                ('status', models.ForeignKey(limit_choices_to={'category': 'wage_value_status'}, on_delete=django.db.models.deletion.PROTECT, related_name='wage_value_periods', to='core.settingoption')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
