# Generated by Django 6.0.2 on 2026-03-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_parent_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='has_dropped_out',
            new_name='has_diploma',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='dropout_date',
            new_name='invoice_paid_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dropout_reason',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_active_student',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_job_guarantee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='invoice_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('offerte', 'Offerte'), ('offerte_akkoord', 'Offerte akkoord'), ('factuur_verstuurd', 'Factuur verstuurd'), ('factuur_betaald', 'Factuur betaald')], max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trajectory_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trajectory_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
