# Generated by Django 6.0.2 on 2026-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_has_dropped_out_studentprofile_has_diploma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dropout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dropout_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_dropped_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_active_student',
            field=models.BooleanField(default=True),
        ),
    ]
